let stockProductos = [
    {id: 1, nombre: "Los Cerros", tipo: "Hotel", desc: "Hotel 5 estrellas", precio: 20000, establecimiento: "Hotel", img: 'https://picsum.photos/200'},
    {id: 2, nombre: "Destino Sur", tipo: "Hotel", desc: "Hotel 4 estrellas", precio: 15000, estabHotelecimiento: "Hotel", img: 'https://picsum.photos/200'},
    {id: 3, nombre: "Chaltén Suites", tipo: "Hotel", desc: "Hotel 4 estrellas", precio: 14000, establecimiento: "Hotel", img: 'https://picsum.photos/200'},
    {id: 4, nombre: "PuduLodge El Chaltén", tipo: "Hotel", desc: "Hotel 3 estrellas", precio: 8000, establecimiento: "Hotel", img: 'https://picsum.photos/200'},
    {id: 5, nombre: "Poicento", tipo: "Hotel", desc: "Hotel 3 estrellas", precio: 8500, establecimiento: "Hotel", img: 'https://picsum.photos/200'},
    {id: 6, nombre: "Lunajuim", tipo: "Hotel", desc: "Hotel 3 estrellas", precio: 8000, establecimiento: "Hotel", img: 'https://picsum.photos/200'},
    {id: 7, nombre: "Pioneros del Valle", tipo: "Hostel", desc: "Hostel", precio: 5000, establecimiento: "Hostel", img: 'https://picsum.photos/200'},
    {id: 8, nombre: "Rancho Grande", tipo: "Hostel", desc: "Hostel", precio: 2900, establecimiento: "Hostel", img: 'https://picsum.photos/200'},
    {id: 9, nombre: "Patagonia Travellers", tipo: "Hostel", desc: "Hostel", precio: 3000, establecimiento: "Hostel", img: 'https://picsum.photos/200'},
    {id: 10, nombre: "Alma Travelers", tipo: "Hostel", desc: "Hostel", precio: 3500, establecimiento: "Hostel", img: 'https://picsum.photos/200'},
    {id: 11, nombre: "Del Lago", tipo: "Hostel", desc: "Hostel", precio: 2500, establecimiento: "Hostel", img: 'https://picsum.photos/200'},
    {id: 12, nombre: "Austral", tipo: "Cabaña", desc: "Cabañas", precio: 6000, establecimiento: "Cabaña", img: 'https://picsum.photos/200'},
    {id: 13, nombre: "La Loma", tipo: "Cabaña", desc: "Cabañas", precio: 6500, establecimiento: "Cabaña", img: 'https://picsum.photos/200'},
    {id: 14, nombre: "Buenavista Chaltén", tipo: "Cabaña", desc: "Cabañas", precio: 7000, establecimiento: "Cabaña", img: 'https://picsum.photos/200'},
    {id: 15, nombre: "Paso del Viento", tipo: "Cabaña", desc: "Cabañas", precio: 7000, establecimiento: "Cabaña", img: 'https://picsum.photos/200'},
    {id: 16, nombre: "El Relincho", tipo: "Cabaña", desc: "Cabañas", precio: 9000, establecimiento: "Cabaña", img: 'https://picsum.photos/200'},
]