let stockProductos = [
    {id: 1, nombre: "Los Cerros", tipo: "Hotel", desc: "Hotel 5 estrellas", precio: 20000, establecimiento: "Hotel", img: 'img/sleep/1LosCerros.jpg'},
    {id: 2, nombre: "Destino Sur", tipo: "Hotel", desc: "Hotel 4 estrellas", precio: 15000, estabHotelecimiento: "Hotel", img: 'img/sleep/2DestinoSur.jpeg'},
    {id: 3, nombre: "Chaltén Suites", tipo: "Hotel", desc: "Hotel 4 estrellas", precio: 14000, establecimiento: "Hotel", img: 'img/sleep/3ChaltenSuites.jpg'},
    {id: 4, nombre: "PuduLodge El Chaltén", tipo: "Hotel", desc: "Hotel 3 estrellas", precio: 8000, establecimiento: "Hotel", img: 'img/sleep/4PuduLodge.jpg'},
    {id: 5, nombre: "Poicenot", tipo: "Hotel", desc: "Hotel 3 estrellas", precio: 8500, establecimiento: "Hotel", img: 'img/sleep/5Poicenot.jpg'},
    {id: 6, nombre: "Lunajuim", tipo: "Hotel", desc: "Hotel 3 estrellas", precio: 8000, establecimiento: "Hotel", img: 'img/sleep/6Lunajuim.jpg'},
    {id: 7, nombre: "Pioneros del Valle", tipo: "Hostel", desc: "Hostel", precio: 5000, establecimiento: "Hostel", img: 'img/sleep/7PionerosDelValle.jpg'},
    {id: 8, nombre: "Rancho Grande", tipo: "Hostel", desc: "Hostel", precio: 2900, establecimiento: "Hostel", img: 'img/sleep/8RanchoGrande.jpg'},
    {id: 9, nombre: "Patagonia Travellers", tipo: "Hostel", desc: "Hostel", precio: 3000, establecimiento: "Hostel", img: 'img/sleep/9PatagoniaTravellers.jpg'},
    {id: 10, nombre: "Alma Travelers", tipo: "Hostel", desc: "Hostel", precio: 3500, establecimiento: "Hostel", img: 'img/sleep/10AlmaTravellers.jpg'},
    {id: 11, nombre: "Del Lago", tipo: "Hostel", desc: "Hostel", precio: 2500, establecimiento: "Hostel", img: 'img/sleep/11DelLago.jpg'},
    {id: 12, nombre: "Austral", tipo: "Cabaña", desc: "Cabañas", precio: 6000, establecimiento: "Cabaña", img: 'img/sleep/12cabaustral.jpg'},
    {id: 13, nombre: "La Loma", tipo: "Cabaña", desc: "Cabañas", precio: 6500, establecimiento: "Cabaña", img: 'img/sleep/13LaLoma.jpg'},
    {id: 14, nombre: "Buenavista Chaltén", tipo: "Cabaña", desc: "Cabañas", precio: 7000, establecimiento: "Cabaña", img: 'img/sleep/14Buenavista.jpg'},
    {id: 15, nombre: "Rivendel", tipo: "Cabaña", desc: "Cabañas", precio: 7000, establecimiento: "Cabaña", img: 'img/sleep/15Rivendel.jpg'},
]