let stockProductos = [
    {id: 1, nombre: "Los Cerros", tipo: "Hotel", desc: "Hotel 5 estrellas", precio: 1200, establecimiento: "Hotel", img: 'https://picsum.photos/200'},
    {id: 2, nombre: "Destino Sur", tipo: "Hotel", desc: "Hotel 4 estrellas", precio: 1100, estabHotelecimiento: "Hotel", img: 'https://picsum.photos/200'},
    {id: 3, nombre: "Chaltén Suites", tipo: "Hotel", desc: "Hotel 4 estrellas", precio: 1200, establecimiento: "Hostel", img: 'https://picsum.photos/200'},
    {id: 4, nombre: "PuduLodge El Chaltén", tipo: "Hotel", desc: "Hotel 3 estrellas", precio: 1400, establecimiento: "Hostel", img: 'https://picsum.photos/200'},
    {id: 5, nombre: "Poicento", tipo: "Hotel", desc: "Hotel 3 estrellas", precio: 1200, establecimiento: "Cabaña", img: 'https://picsum.photos/200'},
    {id: 6, nombre: "Lunajuim", tipo: "Hotel", desc: "Hotel 3 estrellas", precio: 1500, establecimiento: "Cabaña", img: 'https://picsum.photos/200'},
    {id: 7, nombre: "Pioneros del Valle", tipo: "Hostel", desc: "Hostel", precio: 500, establecimiento: "Hotel", img: 'https://picsum.photos/200'},
    {id: 8, nombre: "Rancho Grande", tipo: "Hostel", desc: "Hostel", precio: 500, establecimiento: "Hotel", img: 'https://picsum.photos/200'},
    {id: 9, nombre: "Patagonia Travellers", tipo: "Hostel", desc: "Hostel", precio: 500, establecimiento: "Hostel", img: 'https://picsum.photos/200'},
    {id: 10, nombre: "Alma Travelers", tipo: "Hostel", desc: "Hostel", precio: 700, establecimiento: "Hostel", img: 'https://picsum.photos/200'},
    {id: 11, nombre: "Del Lago", tipo: "Hostel", desc: "Hostel", precio: 700, establecimiento: "Cabaña", img: 'https://picsum.photos/200'},
    {id: 12, nombre: "Austral", tipo: "Cabaña", desc: "Cabañas", precio: 900, establecimiento: "Hotel", img: 'https://picsum.photos/200'},
    {id: 13, nombre: "La Loma", tipo: "Cabaña", desc: "Cabañas", precio: 1400, establecimiento: "Cabaña", img: 'https://picsum.photos/200'},
    {id: 14, nombre: "Buenavista Chaltén", tipo: "Cabaña", desc: "Cabañas", precio: 7000, establecimiento: "Hotel", img: 'https://picsum.photos/200'},
    {id: 15, nombre: "Paso del Viento", tipo: "Cabaña", desc: "Cabañas", precio: 777, establecimiento: "Cabaña", img: 'https://picsum.photos/200'},
    {id: 16, nombre: "El Relincho", tipo: "Cabaña", desc: "Cabañas", precio: 234, establecimiento: "Cabaña", img: 'https://picsum.photos/200'},
]